name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install

    - name: Fix Playwright permissions
      run: chmod +x node_modules/.bin/playwright

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Start server and run tests
      run: |
        npx live-server pages &
        sleep 5
        npx playwright test